version: "3.3"

services:
  server:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./style:/srv/style
      - ./sajt:/srv/sajt
      - ./Materijal:/srv/Materijal
      - ./.hintrc:/srv/.hintrc
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - svetisavasajt_default

networks:
  svetisavasajt_default:
    external: true
